# Configuration file for the research project
project:
  name: "Smart K-Means"
  version: "1.0.0"
  author: "Daniel Cirino Martins"
  description: "Research project"

# Data settings
data:
  raw_path: "raw"
  processed_path: "processed"
  result_path: "result"


datasets:
  - "apucarana_2010.xlsx"
  - "cascavel_2010.xlsx"
  - "foz_iguacu_2010.xlsx"
  - "guarapuava_2010.xlsx"
  - "londrina_2010.xlsx"
  - "maringa_2010.xlsx"
  - "ponta_grossa_2010.xlsx"
  - "toledo_2010.xlsx"


# Model settings
models:
  random_seed: 42
  n_clusters_range: [ 2, 10 ]
  max_iter: 300
  n_init: 10

# Visualization settings
plots:
  style: "seaborn-v0_8"
  figsize: [ 10, 6 ]
  dpi: 300
  save_format: "png"

# Output settings
output:
  results_path: "results"
  figures_path: "results/figures/"
  models_path: "models/"
